POST http://localhost:3000/api/test
Content-Type: application/json

{
    "name": "Xiaomi 19 pro",
    "description": "Xiaomi 13 pro",
    "images": ["snh 1", "snh 2"],
    "idCategory": "661620982af964aba3a62e4a",
    "variations": [
      { 
        "price":  16990000,
        "quantity":15 ,
        "attributes":
            {
                "color": "đỏ"
            }
      },
      {
        "price": 13990000,
        "quantity": 10,
        "attributes":
            {
                "color": "vàng"
            }
      },
      {
        "price": 11990000,
        "quantity": 5,
        "attributes":
            {
                "color": "đen"
            }
      }
    ],
    "discount": {
        "percent": 30,
        "start": "2021-10-01",
        "end": "2021-10-30"
    }
}

###

POST http://localhost:3000/api/test
Content-Type: application/json

 {
    "name": "Samsung Galaxy S22 Ultra",
    "description": "Samsung Galaxy S22 Ultra với công nghệ S-Pen và camera 108 MP.",
    "images": ["galaxys22-img1", "galaxys22-img2"],
    "idCategory": "660b8dd099baa8b459c768d3",
    "variations": [
      {
        "price": 30990000,
        "quantity": 25,
        "attributes": {
          "color": "Phantom Black",
          "ram": "12GB",
          "storage": "512GB"
        }
      },
      {
        "price": 28990000,
        "quantity": 20,
        "attributes": {
          "color": "Burgundy",
          "ram": "8GB",
          "storage": "256GB"
        }
      }
    ],
    "discount": {
      "percent": 15,
      "start": "2023-08-01",
      "end": "2023-08-31"
    }
  }



###
POST http://localhost:3000/api/testAddCategory
Content-Type: application/json

{
    "idParent": "660b8d5c99baa8b459c76890",
    "name": "Xiaomi 13 Series"
}

###
POST http://localhost:3000/api/testUpdateQuantity
Content-Type: application/json

{
    "id": "65ed65e2c3155828e37b0aa6",
    "quantity": 614
}

###
POST http://localhost:3000/api/warranty/6610dd6efa4aa8e85fc63fa5?_method=PUT
Content-Type: application/json

{
    "emial": "phatgowin123@gmail.com"
}

###
POST http://localhost:3000/api/cart
Content-Type: application/json

{
    "idProduct": "6610dd6efa4aa8e85fc63fa5",
    "quantity": 1
}
###
POST http://localhost:3000/api/test
Content-Type: application/json
 {
    "idUser": "6600f1a67e13636c0006b205",
    "note": "hong có gì",
   " total": 20000,
    "status": "Thành công",
    "paymentDetail": {
      "method": "PaymentDetail",
      "status": { type: Boolean },
      "date": { type: Date },
      "amount": { type: Number },
    },
    "details": [
      {
        "price": { type: Number },
        "quantity": { type: Number },
        "idVariation": {
          type: Schema.Types.ObjectId,
          ref: "Product.variations",
        },
      },
    ],
    "shipmentDetail": {
        "name": "đơn hàng",
        "phone":"123",
        "address": "cần thơ"
    },
  },