POST http://localhost:3000/api/test
Content-Type: application/json

{
    "name": "Samsung Ultra s21",
    "description": "Samsung Ultra s21",
    "images": ["snh 1", "snh 2"],
    "idCategory": "660b8d5c99baa8b459c76890",
    "variations": [
      { 
        "price":  7899000,
        "quantity":12 ,
        "attributes":
            {
                "color": "red",
                "ram": "12GB"
            }
      },
      {
        "price": 8990000,
        "quantity": 10,
        "attributes":
            {
                "color": "black",
                "ram": "8GB"
            }
      }
    ],
    "discount": {
        "percent": 0,
        "start": "2021-10-01",
        "end": "2021-10-30"
    }
}
###
POST http://localhost:3000/api/testAddCategory
Content-Type: application/json

{
    "idParent": "660b8d5c99baa8b459c76890",
    "name": "Samsung"
}

###
POST http://localhost:3000/api/testUpdateQuantity
Content-Type: application/json

{
    "id": "65ed65e2c3155828e37b0aa6",
    "quantity": 614
}
