POST http://localhost:3000/api/test
Content-Type: application/json

{
    "name": "Xiaomi 13 pro",
    "description": "Xiaomi 13 pro",
    "images": ["snh 1", "snh 2"],
    "idCategory": "66156c4bb50b2af0420595e7",
    "variations": [
      { 
        "price":  16990000,
        "quantity":15 ,
        "attributes":
            {
                "color": "green",
                "ram": "12GB"
            }
      },
      {
        "price": 13990000,
        "quantity": 10,
        "attributes":
            {
                "color": "black",
                "ram": "8GB"
            }
      }
    ],
    "discount": {
        "percent": 30,
        "start": "2021-10-01",
        "end": "2021-10-30"
    }
}
###
POST http://localhost:3000/api/testAddCategory
Content-Type: application/json

{
    "idParent": "660b8d5c99baa8b459c76890",
    "name": "Xiaomi 13 Series"
}

###
POST http://localhost:3000/api/testUpdateQuantity
Content-Type: application/json

{
    "id": "65ed65e2c3155828e37b0aa6",
    "quantity": 614
}

###
POST http://localhost:3000/api/warranty/6610dd6efa4aa8e85fc63fa5?_method=PUT
Content-Type: application/json

{
    "emial": "phatgowin123@gmail.com"
}